[package]
name = "ropfs"
version = "0.2.1"
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/mlm-games/ropfs"
license = "MIT"
authors = ["mlm-games"]  #["Andre Popovitch <andre@popovit.ch>"]
description = "A Rust implementation of the Origin Private File System browser API (fork)."

[features]
unstable_apis = []

[dependencies]
futures-core = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
web-time = "1.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = { version = "0.4", features = [
    "futures-core-03-stream",
] }
js-sys = "0.3"
base64 = "0.22"
web-sys = { version = "0.3", features = [
    "File",
    "Blob",
    "Navigator",
    "Storage",
    "StorageManager",
    "Window",
    "FileSystemDirectoryHandle",
    "FileSystemFileHandle",
    "FileSystemWritableFileStream",
    "FileSystemGetFileOptions",
    "FileSystemCreateWritableOptions",
    "FileSystemGetDirectoryOptions",
    "FileSystemRemoveOptions",
    "WriteParams",
    "WriteCommandType",
    "FileSystemSyncAccessHandle",
    "FileSystemSyncAccessHandleOptions",
    "FileSystemReadWriteOptions",
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", default-features = false, features = ["fs", "io-util"] }
dirs = "6"
tempfile = "3.27"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
